spring:
  datasource:
    url: jdbc:h2:file:~/cti_print_db;FILE_LOCK=FS
    username: test
    password: test
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
